import Head from "next/head";
import { Box, Button, Center, Divider, Input, Text } from "@chakra-ui/react";
import Layout from "@/components/Layout";
import React, { useEffect, useState } from "react";
import { GetServerSideProps } from "next";
import { signIn, confirmSignIn, getCurrentUser } from "aws-amplify/auth";
import { Amplify } from "aws-amplify";

interface DashboardProps {
    text: string;
}

Amplify.configure({
    Auth: {
        Cognito: {
            userPoolId: "eu-west-2_2vpZhBuJw",
            userPoolClientId: "4b1iq90iad3vje9lb1vdai0qfm",
            loginWith: {
                email: true,
            },
        },
    },
});

export default function Dashboard(props: DashboardProps) {
    return (
        <>
            <Head>
                <title>Upfront - Recruiter Dashboard</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/upfront/svg/favicon-no-background.svg"
                />
            </Head>
            <Layout>
                <Center>
                    <Text>Dashboard</Text>
                </Center>
            </Layout>
        </>
    );
}

export const getServerSideProps = (async (context) => {
    const signedIn = await getCurrentUser();
    console.log("signed in?", signedIn);
    if (!signedIn) {
        return {
            redirect: {
                destination: "/login",
                permanent: false,
            },
        };
    }

    return { props: { text: "hey" } };
}) satisfies GetServerSideProps<DashboardProps>;
