import Head from "next/head";
import { Center, Text } from "@chakra-ui/react";
import Layout from "@/components/Layout";
import React from "react";
import { GetServerSideProps } from "next";
import { isSignedIn } from "./api/signed_in";
import { PageProps } from ".";

export default function Login(props: PageProps) {
    return (
        <>
            <Head>
                <title>Upfront - Login</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/upfront/svg/favicon-no-background.svg"
                />
            </Head>
            <Layout signedIn={props.signedIn}>
                <Center>
                    <Text>Login successful, redirecting to dashboard...</Text>
                </Center>
            </Layout>
        </>
    );
}

export const getServerSideProps = (async (_) => {
    const signedIn = await isSignedIn();

    return { props: { signedIn } };
}) satisfies GetServerSideProps<PageProps>;
