import Head from "next/head";
import React, { useState } from "react";
import {
    Box,
    Button,
    Center,
    Checkbox,
    Divider,
    Fade,
    FormControl,
    FormErrorMessage,
    FormHelperText,
    FormLabel,
    Image,
    Input,
    Radio,
    RadioGroup,
    Select,
    Stack,
    Text,
    useRadio,
    useRadioGroup,
} from "@chakra-ui/react";
import Markdown from "react-markdown";

const SimpleMdeReact = dynamic(() => import("react-simplemde-editor"), {
    ssr: false,
});
import { FC, useCallback } from "react";
import dynamic from "next/dynamic";
import "easymde/dist/easymde.min.css";
import Layout from "@/components/Layout";
import { Currency, JobPost } from "@/components/JobPost";
import { priceFactors } from "@/config";
import { CheckoutSessionResponse } from "./api/checkout_session";
import { PageProps } from ".";
import { isSignedIn } from "./api/signed_in";
import { GetServerSideProps } from "next";
import { JobPostItem } from "./api/checkout_session/[id]";

export type PlanType = "Standard" | "Premium";
export type JobPostStatus = "pending" | "active" | "inactive";

export default function PostJob(props: PageProps) {
    const [step, setStep] = useState(1);
    const [jobValues, setJobValues] = useState<JobPostItem>({
        companyLogoURL: "",
        companyName: "",
        companyWebsite: "http://",
        currency: "GBP",
        howToApply: "",
        location: "",
        description: "",
        maxSalary: 10000,
        minSalary: 5000,
        minYOE: 0,
        title: "",
        visaSponsorship: false,
        loginEmail: "",
        planDuration: 30,
        planType: "Premium",
    });

    const stepTitles: Record<number, string> = {
        1: "Title, Company, Logo and Location",
        2: "Salary, Years Of Experience and Visa Sponsorship",
        3: "Job Description",
        4: "Company/Recruiter Details and How To Apply",
        5: "Duration and Plan",
    };

    return (
        <>
            <Head>
                <title>Upfront - Post a Job</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/upfront/svg/favicon-no-background.svg"
                />
            </Head>
            <Layout signedIn={props.signedIn}>
                <Text fontSize={"2.5rem"} fontWeight={700} my="1rem">
                    Create a Job Post.
                </Text>
                <Text fontWeight={700} fontSize={"2rem"} mb="1rem">
                    We require that companies are{" "}
                    <Text as="span" fontWeight="800" color={"upfront.300"}>
                        Upfront
                    </Text>{" "}
                    about their salaries.
                </Text>
                <Text fontWeight={700} fontSize={"2rem"} mb="1rem">
                    All job postings must contain a salary range.
                </Text>
                <Center>
                    <JobPost {...jobValues} />
                </Center>
                <Divider my="1rem" />
                <Box
                    p="1rem"
                    my="1rem"
                    borderRadius={"1px"}
                    borderColor={"upfront.300"}
                >
                    <Text
                        my="1rem"
                        fontWeight={700}
                        fontSize={"2rem"}
                        mb="1rem"
                    >
                        Step {step} of 5 - {stepTitles[step]}
                    </Text>
                    {step === 1 && (
                        <Fade in={step === 1}>
                            <Step1
                                jobValues={jobValues}
                                setJobValues={setJobValues}
                                setStep={setStep}
                            />
                        </Fade>
                    )}
                    {step === 2 && (
                        <Fade in={step === 2}>
                            <Step2
                                jobValues={jobValues}
                                setJobValues={setJobValues}
                                setStep={setStep}
                            />
                        </Fade>
                    )}

                    {step === 3 && (
                        <Fade in={step === 3}>
                            <Step3
                                jobValues={jobValues}
                                setJobValues={setJobValues}
                                setStep={setStep}
                            />
                        </Fade>
                    )}

                    {step === 4 && (
                        <Fade in={step === 4}>
                            <Step4
                                jobValues={jobValues}
                                setJobValues={setJobValues}
                                setStep={setStep}
                            />
                        </Fade>
                    )}

                    {step === 5 && (
                        <Fade in={step === 5}>
                            <Step5
                                jobValues={jobValues}
                                setJobValues={setJobValues}
                                setStep={setStep}
                            />
                        </Fade>
                    )}
                </Box>
            </Layout>
        </>
    );
}

export const getServerSideProps = (async (_) => {
    const signedIn = await isSignedIn();

    return { props: { signedIn } };
}) satisfies GetServerSideProps<PageProps>;

const Step1 = ({
    jobValues,
    setJobValues,
    setStep,
}: {
    jobValues: JobPostFormProps;
    setJobValues: React.Dispatch<React.SetStateAction<JobPostFormProps>>;
    setStep: React.Dispatch<React.SetStateAction<number>>;
}) => {
    const handleSubmit = (event: any) => {
        event.preventDefault();
        setStep(2);
    };
    return (
        <form onSubmit={handleSubmit}>
            <FormControl isRequired>
                <FormLabel>Job Title</FormLabel>
                <Input
                    size={"lg"}
                    id="title"
                    maxLength={45}
                    type="text"
                    placeholder="Job Title"
                    onChange={(e) =>
                        setJobValues({
                            ...jobValues,
                            title: e.target.value,
                        })
                    }
                    value={jobValues.title}
                />
                <FormHelperText>
                    Enter the title of the role you are advertising, for
                    example, Software Engineer.
                </FormHelperText>
            </FormControl>
            <Divider my="1rem" />

            <FormControl isRequired>
                <FormLabel>Company Name</FormLabel>
                <Input
                    size={"lg"}
                    id="companyName"
                    type="text"
                    placeholder="Company Name"
                    onChange={(e) =>
                        setJobValues({
                            ...jobValues,
                            companyName: e.target.value,
                        })
                    }
                    value={jobValues.companyName}
                />
                <FormHelperText>
                    Enter the name of the company you are advertising the role
                    for.
                </FormHelperText>
            </FormControl>
            <Divider my="1rem" />

            <FormControl isRequired>
                <FormLabel>Company Logo URL</FormLabel>
                <Input
                    size={"lg"}
                    id="companyLogoURL"
                    type="file"
                    accept="image/*"
                    placeholder="Company Logo URL"
                    onChange={(e) => {
                        if (e.target.files) {
                            const file = URL.createObjectURL(
                                e.target.files[0] as File
                            );
                            setJobValues({
                                ...jobValues,
                                companyLogoURL: file,
                            });
                        }
                    }}
                />
                <Center my="1rem">
                    {jobValues.companyLogoURL === "" ? (
                        <Text>Logo Preview</Text>
                    ) : (
                        <Image
                            src={jobValues.companyLogoURL}
                            alt="Company logo"
                            maxWidth={{
                                base: "50px",
                                md: "100px",
                            }}
                            maxHeight={{
                                base: "50px",
                                md: "100px",
                            }}
                            borderRadius={"5px"}
                        />
                    )}
                </Center>

                <FormHelperText>
                    Enter the URL of the logo you would like displayed on your
                    job advert, for example:
                    https://en.wikipedia.org/wiki/File:Google_2015_logo.svg
                    <br />
                    Data URLs will also work, for example:
                    data:image/png;base64,iVBORw0KGgoAAAANSUh...
                </FormHelperText>
            </FormControl>
            <Divider my={"1rem"} />
            <FormControl isRequired>
                <FormLabel>Location</FormLabel>
                <Input
                    size={"lg"}
                    id="location"
                    type="text"
                    placeholder="Location"
                    onChange={(e) =>
                        setJobValues({
                            ...jobValues,
                            location: e.target.value.toLocaleUpperCase(),
                        })
                    }
                    value={jobValues.location}
                />
                <FormHelperText>
                    Enter the Location of where the Job will be located e.g.
                    London, UK, feel free to put remote if the job can be done
                    from anywhere!
                </FormHelperText>
            </FormControl>
            <Divider my="1rem" />
            <Stack direction={["column", "row"]} width={"100%"} my="1rem">
                <Button
                    type="submit"
                    color="white"
                    backgroundColor={"upfront.300"}
                >
                    Continue
                </Button>
            </Stack>
        </form>
    );
};

const Step2 = ({
    jobValues,
    setJobValues,
    setStep,
}: {
    jobValues: JobPostFormProps;
    setJobValues: React.Dispatch<React.SetStateAction<JobPostFormProps>>;
    setStep: React.Dispatch<React.SetStateAction<number>>;
}) => {
    const handleSubmit = (event: any) => {
        event.preventDefault();
        setStep(3);
    };

    const isError = jobValues.minSalary > jobValues.maxSalary;

    return (
        <form onSubmit={handleSubmit}>
            <FormControl isRequired>
                <FormLabel>Minimum Salary Offered</FormLabel>
                <Input
                    size={"lg"}
                    id="minSalary"
                    maxLength={45}
                    type="number"
                    placeholder="Minimum Salary"
                    onChange={(e) =>
                        setJobValues({
                            ...jobValues,
                            minSalary: +e.target.value,
                        })
                    }
                    value={jobValues.minSalary}
                />
                <FormHelperText>
                    Enter the minimum salary you would offer for this role,
                    regardless of experience.
                </FormHelperText>
            </FormControl>
            <Divider my="1rem" />

            <FormControl isInvalid={isError} isRequired>
                <FormLabel>Maximum Salary Offered</FormLabel>
                <Input
                    size={"lg"}
                    id="maxSalary"
                    maxLength={45}
                    type="number"
                    placeholder="Maximum Salary"
                    onChange={(e) =>
                        setJobValues({
                            ...jobValues,
                            maxSalary: +e.target.value,
                        })
                    }
                    value={jobValues.maxSalary}
                />
                {!isError ? (
                    <FormHelperText>
                        Enter the maximum salary you would offer for this role,
                        regardless of experience.
                    </FormHelperText>
                ) : (
                    <FormErrorMessage>
                        Maximum salary must be greater than or equal to minimum
                        salary!
                    </FormErrorMessage>
                )}
            </FormControl>
            <Divider my="1rem" />

            <FormControl isRequired>
                <FormLabel>Currency</FormLabel>
                <Select
                    size={"lg"}
                    id="currency"
                    onChange={(e) =>
                        setJobValues({
                            ...jobValues,
                            currency: e.target.value as Currency,
                        })
                    }
                >
                    <option>GBP</option>
                    <option>USD</option>
                    <option>EUR</option>
                    <option>AUD</option>
                    <option>CAD</option>
                    <option>SGD</option>
                    <option>CHF</option>
                    <option>INR</option>
                    <option>JPY</option>
                </Select>
                <FormHelperText>
                    Choose the currency for which the salary will be paid in.
                </FormHelperText>
            </FormControl>
            <Divider my="1rem" />

            <FormControl isRequired>
                <FormLabel>Minimum Years of Experience Required</FormLabel>
                <Select
                    size={"lg"}
                    id="minYOE"
                    onChange={(e) =>
                        setJobValues({
                            ...jobValues,
                            minYOE: +e.target.value.replace("+", ""),
                        })
                    }
                >
                    <option>0+</option>
                    <option>1+</option>
                    <option>2+</option>
                    <option>3+</option>
                    <option>4+</option>
                    <option>5+</option>
                    <option>6+</option>
                    <option>7+</option>
                    <option>8+</option>
                    <option>9+</option>
                    <option>10+</option>
                    <option>11+</option>
                    <option>12+</option>
                </Select>
                <FormHelperText>
                    Enter the minimum years of expired required to be considered
                    for the role.
                </FormHelperText>
            </FormControl>
            <Divider my="1rem" />

            <FormControl>
                <Checkbox
                    size={"lg"}
                    id="visaSponsorship"
                    onChange={(e) => {
                        setJobValues({
                            ...jobValues,
                            visaSponsorship: e.target.checked,
                        });
                    }}
                >
                    VISA Sponsorship offered?
                </Checkbox>
                <FormHelperText>
                    Check this box if you can offer VISA Sponsorship.
                </FormHelperText>
            </FormControl>

            <Divider my="1rem" />
            <Stack direction={["column", "row"]} width={"100%"} my="1rem">
                <Button onClick={() => setStep(1)}>Back</Button>
                <Button
                    type="submit"
                    color="white"
                    backgroundColor={"upfront.300"}
                >
                    Continue
                </Button>
            </Stack>
        </form>
    );
};

const Step3 = ({
    jobValues,
    setJobValues,
    setStep,
}: {
    jobValues: JobPostFormProps;
    setJobValues: React.Dispatch<React.SetStateAction<JobPostFormProps>>;
    setStep: React.Dispatch<React.SetStateAction<number>>;
}) => {
    const handleSubmit = (event: any) => {
        event.preventDefault();
        setStep(4);
    };

    const onChange = useCallback(
        (value: string) => {
            setJobValues({ ...jobValues, description: value });
        },
        [jobValues, setJobValues]
    );

    const isError = jobValues.description === "";
    return (
        <form onSubmit={handleSubmit}>
            <FormControl isInvalid={isError} isRequired>
                <FormLabel>Job Post Description</FormLabel>

                <SimpleMdeReact
                    id="description"
                    style={{
                        width: "100%",
                    }}
                    onChange={onChange}
                    value={jobValues.description}
                />
                <FormHelperText>
                    Enter the job description, the above editor allows you to
                    write in markdown.
                </FormHelperText>
            </FormControl>
            <Divider my="1rem" />
            <FormLabel>Preview</FormLabel>
            <Box
                border="1px"
                borderRadius={"5px"}
                borderColor={"gray.200"}
                padding={"2rem"}
            >
                <Text>
                    <Markdown>{jobValues.description}</Markdown>
                </Text>
            </Box>
            <Stack direction={["column", "row"]} width={"100%"} my="1rem">
                <Button onClick={() => setStep(2)}>Back</Button>
                <Button
                    type="submit"
                    color="white"
                    backgroundColor={"upfront.300"}
                    isDisabled={isError}
                >
                    Continue
                </Button>
            </Stack>
        </form>
    );
};

const Step4 = ({
    jobValues,
    setJobValues,
    setStep,
}: {
    jobValues: JobPostFormProps;
    setJobValues: React.Dispatch<React.SetStateAction<JobPostFormProps>>;
    setStep: React.Dispatch<React.SetStateAction<number>>;
}) => {
    const handleSubmit = (event: any) => {
        event.preventDefault();
        setStep(5);
    };
    const [howToApply, setHowToApply] = useState("url");

    return (
        <form onSubmit={handleSubmit}>
            <FormControl
                isInvalid={jobValues.companyWebsite === "http://"}
                isRequired
            >
                <FormLabel>Company Website</FormLabel>
                <Input
                    size={"lg"}
                    id="companyWebsite"
                    maxLength={45}
                    type="url"
                    placeholder="http://example.com"
                    onChange={(e) =>
                        setJobValues({
                            ...jobValues,
                            companyWebsite: e.target.value,
                        })
                    }
                    value={
                        jobValues.companyWebsite === ""
                            ? "http://"
                            : jobValues.companyWebsite
                    }
                />
                <FormHelperText>
                    Enter your companies website. Please include either the
                    http:// or https:// prefix.
                </FormHelperText>
            </FormControl>
            <Divider my="1rem" />

            <FormControl isRequired>
                <FormLabel>
                    How would you like to receive applications?
                </FormLabel>
                <RadioGroup onChange={setHowToApply} value={howToApply}>
                    <Stack direction="row">
                        <Radio value="url">Via a link to your website</Radio>
                        <Radio value="email">Via email</Radio>
                    </Stack>
                </RadioGroup>
                {howToApply === "url" ? (
                    <>
                        <Input
                            size={"lg"}
                            id="howToApplyWebsite"
                            type="url"
                            placeholder="http://example.com/apply"
                            onChange={(e) =>
                                setJobValues({
                                    ...jobValues,
                                    howToApply: e.target.value,
                                })
                            }
                            value={jobValues.howToApply}
                        />
                        <FormHelperText>
                            Enter the URL the applicant should be directed to
                            when they click apply. Please include either the
                            http:// or https:// prefix.
                        </FormHelperText>
                    </>
                ) : (
                    <>
                        <Input
                            size={"lg"}
                            id="howToApplyEmail"
                            type="email"
                            placeholder="jobs@upfrontjobs.co.uk"
                            onChange={(e) =>
                                setJobValues({
                                    ...jobValues,
                                    howToApply: e.target.value,
                                })
                            }
                            value={jobValues.howToApply}
                        />
                        <FormHelperText>
                            Enter the email address the applicant should use to
                            contact the recruiter about this job.
                        </FormHelperText>
                    </>
                )}
            </FormControl>

            <Divider my="1rem" />

            <FormControl isRequired>
                <FormLabel>Your Login Email</FormLabel>
                <Input
                    size={"lg"}
                    id="loginEmail"
                    type="text"
                    placeholder={`johnsmith@${jobValues.companyName.toLocaleLowerCase()}.com`}
                    onChange={(e) =>
                        setJobValues({
                            ...jobValues,
                            loginEmail: e.target.value,
                        })
                    }
                    value={jobValues.loginEmail}
                />
                <FormHelperText>
                    Enter the email address you (the recruiter/hiring manager)
                    will use to log in to Upfront and manage/view your job
                    posts.
                </FormHelperText>
            </FormControl>
            <Divider my="1rem" />
            <Stack direction={["column", "row"]} width={"100%"} my="1rem">
                <Button onClick={() => setStep(3)}>Back</Button>
                <Button
                    type="submit"
                    color="white"
                    backgroundColor={"upfront.300"}
                >
                    Continue
                </Button>
            </Stack>
        </form>
    );
};

const Step5 = ({
    jobValues,
    setJobValues,
    setStep,
}: {
    jobValues: JobPostFormProps;
    setJobValues: React.Dispatch<React.SetStateAction<JobPostFormProps>>;
    setStep: React.Dispatch<React.SetStateAction<number>>;
}) => {
    const [isLoading, setIsLoading] = useState(false);
    const handleSubmit = async (event: any) => {
        event.preventDefault();
        setIsLoading(true);
        const checkoutSessionResponse = await fetch("/api/checkout_session", {
            method: "POST",
            body: JSON.stringify(jobValues || {}),
        });

        const data: CheckoutSessionResponse =
            await checkoutSessionResponse.json();

        window.location.href = data.url;
        setIsLoading(false);
    };
    return (
        <form onSubmit={handleSubmit}>
            <FormControl isRequired>
                <FormLabel>Plan Duration</FormLabel>
                <Select
                    size={"lg"}
                    id="planDuration"
                    background={"white"}
                    color="black"
                    width={{ base: "100%" }}
                    onChange={(e) =>
                        setJobValues({
                            ...jobValues,
                            planDuration: +e.target.value,
                        })
                    }
                    value={jobValues.planDuration}
                >
                    {[1, 2, 3, 4, 5, 6].map((x) => {
                        return (
                            <option key={x * 30} value={x * 30}>
                                {x * 30} Days
                            </option>
                        );
                    })}
                </Select>
            </FormControl>
            <Divider my="1rem" />
            <PlanTypes
                duration={jobValues.planDuration}
                jobValues={jobValues}
                setJobValues={setJobValues}
            />

            <Divider my="1rem" />
            <Stack direction={["column", "row"]} width={"100%"} my="1rem">
                <Button onClick={() => setStep(4)}>Back</Button>
                <Button
                    type="submit"
                    color="white"
                    backgroundColor={"upfront.300"}
                    isLoading={isLoading}
                >
                    Continue To Payment
                </Button>
            </Stack>
        </form>
    );
};

const PlanTypes: FC<{
    jobValues: JobPostFormProps;
    setJobValues: React.Dispatch<React.SetStateAction<JobPostFormProps>>;
    duration: number;
}> = ({ jobValues, setJobValues, duration }) => {
    const { getRadioProps } = useRadioGroup({
        name: "planType",
        onChange: (next) =>
            setJobValues({ ...jobValues, planType: next as PlanType }),
        value: jobValues.planType,
    });

    return (
        <FormControl isRequired>
            <FormLabel>Plan Type</FormLabel>
            <Stack direction={["column", "row"]} width={"100%"}>
                {["Standard" as PlanType, "Premium" as PlanType].map(
                    (value: PlanType) => {
                        const radio = getRadioProps({ value });
                        return (
                            <RadioCard
                                key={value}
                                duration={duration}
                                planType={value}
                                {...radio}
                            >
                                {value}
                            </RadioCard>
                        );
                    }
                )}
            </Stack>
        </FormControl>
    );
};

const RadioCard: FC<any> = (props) => {
    const { getInputProps, getCheckboxProps } = useRadio(props);

    const input = getInputProps();
    const checkbox = getCheckboxProps();

    return (
        <Box as="label" width={{ base: "100%", md: "50%" }}>
            <input {...input} />
            <Box
                {...checkbox}
                textAlign={"center"}
                padding="1rem"
                border={"1px solid"}
                borderRadius="5px"
                borderColor={"upfront.300"}
                background={"white"}
                color="black"
                fontSize={"1.5rem"}
                boxShadow={"lg"}
                cursor="pointer"
                borderWidth="1px"
                _checked={{
                    bg: "upfront.300",
                    color: "white",
                    borderColor: "upfront.300",
                }}
                _focus={{
                    boxShadow: "outline",
                }}
                px={5}
                py={3}
            >
                <Text fontSize={"2rem"}>The {props.children} Plan</Text>
                <Text fontWeight={800} fontSize={"2rem"}>
                    £
                    {(props.duration *
                        priceFactors[props.planType as PlanType]) /
                        30}
                </Text>
                {props.children}
            </Box>
        </Box>
    );
};

export interface JobPostFormProps {
    companyLogoURL: string;
    companyName: string;
    companyWebsite: string;
    currency: Currency;
    description: string;
    howToApply: string;
    location: string;
    maxSalary: number;
    minSalary: number;
    minYOE: number;
    title: string;
    visaSponsorship: boolean;
    loginEmail: string;
    planDuration: number;
    planType: PlanType;
}
