import Head from "next/head";
import { Box, Button, Input, Text } from "@chakra-ui/react";
import JobSearch from "@/components/JobSearch";
import { Abel } from "next/font/google";
import Layout from "@/components/Layout";
import { GetServerSideProps } from "next";
import { JobPost, JobPostProps, JobPostRecord } from "@/components/JobPost";
import React from "react";

export default function SignIn() {
    return (
        <>
            <Head>
                <title>Upfront - Jobs</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/upfront/svg/favicon-no-background.svg"
                />
            </Head>
            <Layout>
                <Input type="email"></Input>
                <Button>Submit</Button>
            </Layout>
        </>
    );
}

// export const getServerSideProps = (async () => {
//     // Fetch data from external API
//     const { rows } = await sql`SELECT * from job_posts WHERE status = 'active'`;
//     const jobs: JobPostRecord[] = rows as JobPostRecord[];
//     const cleanedJobs: JobPostProps[] = jobs.map((x: JobPostRecord) => {
//         return {
//             ...x,
//             createdAt: x.createdAt?.toISOString(),
//             updatedAt: x.updatedAt?.toISOString(),
//         };
//     });
//     // Pass data to the page via props
//     return { props: { jobs: cleanedJobs } };
// }) satisfies GetServerSideProps<{ jobs: JobPostProps[] }>;
