import Head from "next/head";
import { Button, Text } from "@chakra-ui/react";
import Layout from "@/components/Layout";
import { JobPost } from "@/components/JobPost";
import { GetServerSideProps } from "next";
import { getCheckoutSession, JobPostItem } from "./api/checkout_session/[id]";
import { PageProps } from ".";
import { isSignedIn } from "./api/signed_in";
import { useRouter } from "next/router";

interface SuccessProps extends PageProps {
    jobPost: JobPostItem;
}
export default function Success({ jobPost, signedIn }: SuccessProps) {
    const router = useRouter();
    return (
        <>
            <Head>
                <title>Upfront - Jobs</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/upfront/svg/favicon-no-background.svg"
                />
            </Head>
            <Layout signedIn={signedIn}>
                <Text
                    fontSize={"2.5rem"}
                    my="1rem"
                    fontWeight="800"
                    color={"upfront.300"}
                >
                    Payment Success
                </Text>
                <Text fontSize={"2rem"} mb="1rem">
                    An email has been sent to {jobPost.loginEmail} confirming
                    your plan purchase. <br />
                    You may now sign in to the Upfront portal to view/manage
                    your job posts!
                </Text>
                {!signedIn && (
                    <Button
                        display={{ base: "none", md: "inline-flex" }}
                        fontSize={"1rem"}
                        fontWeight={600}
                        color={"white"}
                        bg={"upfront.300"}
                        onClick={() => router.push("/login")}
                        _hover={{
                            bg: "upfront.200",
                        }}
                        mb={"1rem"}
                    >
                        Recruiter Log In
                    </Button>
                )}

                {jobPost ? <JobPost {...jobPost} /> : "loading..."}
            </Layout>
        </>
    );
}

export const getServerSideProps = (async (context) => {
    const checkoutSessionResponse: JobPostItem = await getCheckoutSession(
        context.query.id as string
    );
    const signedIn = await isSignedIn();

    return { props: { jobPost: checkoutSessionResponse, signedIn } };
}) satisfies GetServerSideProps<SuccessProps>;
