import Head from "next/head";
import { Text } from "@chakra-ui/react";
import Layout from "@/components/Layout";
import useSWR from "swr";
import { useRouter } from "next/router";
import { JobPost, JobPostProps } from "@/components/JobPost";

export default function Success() {
    const router = useRouter();
    // const { data, error } = useSWR(
    //     router.query.session_id
    //         ? `/api/checkout_sessions/${router.query.session_id}`
    //         : null,
    //     fetchGetJSON
    // );

    // if (error) return <div>failed to load</div>;

    return (
        <>
            <Head>
                <title>Upfront - Jobs</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/upfront/svg/favicon-no-background.svg"
                />
            </Head>
            <Layout>
                <Text
                    fontSize={"2.5rem"}
                    my="1rem"
                    fontWeight="800"
                    color={"upfront.300"}
                >
                    Success
                </Text>
                <Text fontWeight={700} fontSize={"2rem"} mb="1rem">
                    Where{" "}
                    <Text as="span" fontWeight="800" color={"upfront.300"}>
                        salaries
                    </Text>{" "}
                    are always{" "}
                    <Text as="span" fontWeight="800" color={"upfront.300"}>
                        provided.
                    </Text>
                </Text>
                {/* {data ? <JobPost {...(data as JobPostProps)} /> : "loading..."} */}
            </Layout>
        </>
    );
}
