import Head from "next/head";
import { Text } from "@chakra-ui/react";
import Layout from "@/components/Layout";
import useSWR from "swr";
import { useRouter } from "next/router";
import { JobPost, JobPostProps } from "@/components/JobPost";
import { GetServerSideProps } from "next";
import { getCheckoutSession } from "./api/checkout_session/[id]";

export default function Success({ jobPost }: { jobPost: JobPostProps }) {
    return (
        <>
            <Head>
                <title>Upfront - Jobs</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/upfront/svg/favicon-no-background.svg"
                />
            </Head>
            <Layout>
                <Text
                    fontSize={"2.5rem"}
                    my="1rem"
                    fontWeight="800"
                    color={"upfront.300"}
                >
                    Success
                </Text>
                <Text fontWeight={700} fontSize={"2rem"} mb="1rem">
                    Where{" "}
                    <Text as="span" fontWeight="800" color={"upfront.300"}>
                        salaries
                    </Text>{" "}
                    are always{" "}
                    <Text as="span" fontWeight="800" color={"upfront.300"}>
                        provided.
                    </Text>
                </Text>
                {jobPost ? <JobPost {...jobPost} /> : "loading..."}
            </Layout>
        </>
    );
}

export const getServerSideProps = (async (context) => {
    const checkoutSessionResponse: JobPostProps = await getCheckoutSession(
        context.query.id as string
    );
    return { props: { jobPost: checkoutSessionResponse } };
}) satisfies GetServerSideProps<{ jobPost: JobPostProps }>;
