CREATE TABLE job_posts (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    title VARCHAR(255) NOT NULL,
    "companyLogo" VARCHAR(255) NOT NULL,
    "companyName" VARCHAR(255) NOT NULL,
    "companyWebsite" VARCHAR(255) NOT NULL,
    currency VARCHAR(8) NOT NULL,
    description TEXT NOT NULL,
    location VARCHAR(255) NOT NULL,
    "minSalary" integer NOT NULL,
    "maxSalary" integer NOT NULL,
    "loginEmail" VARCHAR(255) NOT NULL,
    "howToApply" VARCHAR(255) NOT NULL,
    "visaSponsorship" boolean NOT NULL DEFAULT FALSE,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    "planType" VARCHAR(50) NOT NULL,
    "planDuration" integer NOT NULL,
    "totalAmount" decimal NOT NULL,
    "paymentIntentId" VARCHAR(50),
    "checkoutSessionId" VARCHAR(255) NOT NULL,
    "createdAt" TIMESTAMP NOT NULL,
    "updatedAt" TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc')
);