import Head from "next/head";
import Navbar from "../components/Navbar";
import { Box, Container, HStack, Text } from "@chakra-ui/react";
import JobSearch from "@/components/JobSearch";
import { useRouter } from "next/router";
import { Abel } from "next/font/google";
import Layout from "@/components/Layout";
import { GetServerSideProps } from "next";
import { JobPost, JobPostProps } from "./job-post";
import { sql } from "@vercel/postgres";
import { copy } from "@vercel/blob";

const abel = Abel({
    subsets: ["latin"],
    display: "swap",
    weight: "400",
});

export default function Home({ jobs }: { jobs: JobPostProps[] }) {
    return (
        <>
            <Head>
                <title>Upfront - Jobs</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/upfront/svg/favicon-no-background.svg"
                />
            </Head>
            <Layout>
                <Text fontSize={"2.5rem"} fontWeight={700} my="1rem">
                    Don&apos;t waste time. Be{" "}
                    <Text as="span" fontWeight="800" color={"upfront.300"}>
                        Upfront.
                    </Text>
                </Text>
                <Text fontWeight={700} fontSize={"2rem"} mb="1rem">
                    Where{" "}
                    <Text as="span" fontWeight="800" color={"upfront.300"}>
                        salaries
                    </Text>{" "}
                    are always{" "}
                    <Text as="span" fontWeight="800" color={"upfront.300"}>
                        provided.
                    </Text>
                </Text>
                <JobSearch />
                <Box my="1rem">
                    {jobs.map((x, i) => {
                        return (
                            <Box my="1rem" key={i}>
                                <JobPost {...x} />
                            </Box>
                        );
                    })}
                </Box>
            </Layout>
        </>
    );
}

export const getServerSideProps = (async () => {
    // Fetch data from external API
    const { rows } = await sql`SELECT * from job_posts`;
    const jobs: JobPostProps[] = rows.map((x) => {
        return {
            companyLogo: "",
            companyName: x.company_name,
            companyWebsite: x.company_website,
            currency: x.currency,
            description: x.description,
            howToApply: x.how_to_apply,
            location: x.location,
            maxSalary: x.max_salary,
            minSalary: x.min_salary,
            title: x.title,
            visaSponsorship: x.visa_sponsorship,
            yourEmail: x.login_email,
        };
    });
    // Pass data to the page via props
    return { props: { jobs: jobs } };
}) satisfies GetServerSideProps<{ jobs: JobPostProps[] }>;
