import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "../components/Navbar";
import {
    AbsoluteCenter,
    Box,
    Button,
    Center,
    Container,
    Divider,
    HStack,
    Image,
    Input,
    Link,
    ListItem,
    Radio,
    RadioGroup,
    Stack,
    Text,
    UnorderedList,
    VStack,
} from "@chakra-ui/react";
import JobSearch from "@/components/JobSearch";
import { useRouter } from "next/router";
import { Abel } from "next/font/google";
import { useState } from "react";
import * as EmailValidator from "email-validator";

const abel = Abel({
    subsets: ["latin"],
    display: "swap",
    weight: "400",
});

export default function Home() {
    const router = useRouter();
    const [value, setValue] = useState("1");
    const [email, setEmail] = useState("");
    const [emailError, setEmailError] = useState<string | undefined>(undefined);

    const handleEmailInput = (e: string) => {
        if (e === "") {
            setEmailError(undefined);
            return;
        }
        if (EmailValidator.validate(e)) {
            setEmailError(undefined);
            setEmail(e);
            return;
        } else {
            if (e !== "") {
                setEmailError("Please enter a valid email.");
                return;
            }
        }
    };

    const submit = () => {
        console.log(email);
    };

    return (
        <>
            <Head>
                <title>Upfront - Coming Soon</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/upfront/svg/favicon-no-background.svg"
                />
            </Head>
            <main>
                <Box
                    position="relative"
                    h="100vh"
                    background="transparent"
                    p={{ base: "0", md: "4rem" }}
                >
                    <Box p="1rem" background="upfront.300">
                        <Stack
                            direction={["column", "row"]}
                            alignItems={"center"}
                            justifyContent={"space-between"}
                        >
                            <Image
                                src="/upfront/svg/logo-no-background-white.svg"
                                width="12rem"
                            />
                            <Text
                                fontSize={"2rem"}
                                fontWeight={700}
                                color="white"
                                mb="1rem"
                                className={abel.className}
                            >
                                UPFRONT JOBS IS LAUNCHING SOON
                            </Text>
                        </Stack>

                        <Divider mb="1rem" />
                        <Stack
                            direction={["column", "row"]}
                            alignItems={"center"}
                        >
                            <VStack
                                alignItems={"left"}
                                width={{ base: "100%", md: "50%" }}
                                minH={"100%"}
                                m="0.5rem"
                                className={abel.className}
                            >
                                <Center>
                                    <Text fontWeight={700}>
                                        For Job Seekers
                                    </Text>
                                </Center>

                                <Box
                                    borderRadius={"5px"}
                                    background={"white"}
                                    color={"black"}
                                    p={"1rem"}
                                >
                                    <UnorderedList>
                                        <ListItem>
                                            <Text as={"span"} fontWeight={600}>
                                                Upfront Job Posts{" "}
                                            </Text>
                                            - Upfront will be a platform where
                                            job postings are carefully curated
                                            to ensure accurate salary ranges are
                                            listed. <br />
                                            We're tired of companies obscuring
                                            the salary offered for a role until
                                            it's revealed too late into the
                                            application process, we believe that
                                            companies should be Upfront about
                                            the salary offered and employers
                                            will be <b>required</b> to list the
                                            salary range in any job post on
                                            Upfront.
                                        </ListItem>
                                        <ListItem>
                                            <Text as={"span"} fontWeight={600}>
                                                Developer profiles{" "}
                                            </Text>
                                            - you can <b>showcase yourself</b>{" "}
                                            as a prospective employee. <br />
                                            Including the roles you are looking
                                            for, the location you desire to work
                                            in and the skills you possess.
                                            Employers will then be able to reach
                                            out directly to you via Upfront.
                                        </ListItem>
                                    </UnorderedList>
                                </Box>
                            </VStack>
                            <VStack
                                alignItems={"left"}
                                width={{ base: "100%", md: "50%" }}
                                minH={"100%"}
                                m="0.5rem"
                                className={abel.className}
                            >
                                <Center>
                                    <Text fontWeight={700}>For Employers</Text>
                                </Center>

                                <Box
                                    borderRadius={"5px"}
                                    background={"white"}
                                    color={"black"}
                                    p={"1rem"}
                                >
                                    <UnorderedList>
                                        <ListItem>
                                            <Text as={"span"} fontWeight={600}>
                                                Performance analytics{" "}
                                            </Text>
                                            - Upfront will provide dynamically
                                            updating data-driven insights into
                                            job post performance, this will
                                            include clicks into the application
                                            on our end as well as clicks through
                                            to where they can apply on your end.
                                        </ListItem>
                                        <ListItem>
                                            <Text as={"span"} fontWeight={600}>
                                                Fair pricing{" "}
                                            </Text>
                                            - we promise to remain transparent
                                            and competitive in our pricing when
                                            compared to other job advertisement
                                            websites.
                                        </ListItem>
                                        <ListItem>
                                            <Text as={"span"} fontWeight={600}>
                                                Listing salary ranges boost job
                                                post performance{" "}
                                            </Text>
                                            -{" "}
                                            <Link
                                                fontWeight={700}
                                                color={"upfront.300"}
                                                target="_blank"
                                                href="https://www.reed.co.uk/recruiter-advice/why-you-should-always-state-salary-in-your-job-ads"
                                            >
                                                Reed
                                            </Link>{" "}
                                            have found that job posts which
                                            disclose salary receive 60% more
                                            applications than those who do not.
                                        </ListItem>
                                        <ListItem>
                                            As an employer, if you sign up to
                                            our prelaunch using the form below,
                                            we will give you 5 free month-long
                                            job posts.
                                        </ListItem>
                                    </UnorderedList>
                                </Box>
                            </VStack>
                        </Stack>
                        <Divider my="1rem" />
                        <Box className={abel.className}>
                            <Text fontSize={"2rem"} fontWeight={700} ml="1rem">
                                Sign up to be the first to know when we launch!
                            </Text>
                            <Stack
                                direction={["column", "row"]}
                                borderRadius={"5px"}
                                color={"white"}
                                p={"1rem"}
                                gap={"2rem"}
                                alignItems={"center"}
                            >
                                <Box>
                                    <Stack
                                        direction={["column", "row"]}
                                        alignItems={"center"}
                                    >
                                        <Box>
                                            <Text fontSize="2rem">
                                                Are you a job seeker or an
                                                employer?
                                            </Text>
                                        </Box>
                                        <Box>
                                            <RadioGroup
                                                onChange={setValue}
                                                value={value}
                                                fontSize={"2rem"}
                                            >
                                                <Stack direction="row">
                                                    <Radio
                                                        background="white"
                                                        value="1"
                                                    >
                                                        Job Seeker
                                                    </Radio>
                                                    <Radio
                                                        background="white"
                                                        value="2"
                                                    >
                                                        Employer
                                                    </Radio>
                                                </Stack>
                                            </RadioGroup>
                                        </Box>
                                    </Stack>
                                </Box>
                                <Box>
                                    <Stack
                                        direction={["column", "row"]}
                                        alignItems={"center"}
                                    >
                                        <Box>
                                            <Text fontSize="2rem">
                                                Please enter an email:
                                            </Text>
                                        </Box>
                                        <Box>
                                            <Input
                                                background="white"
                                                type="email"
                                                color="black"
                                                onChange={(e) =>
                                                    handleEmailInput(
                                                        e.target.value
                                                    )
                                                }
                                            />
                                            {emailError && (
                                                <Text color={"white"}>
                                                    Email no good
                                                </Text>
                                            )}
                                        </Box>
                                    </Stack>
                                </Box>
                                <Box>
                                    <Button onClick={() => submit()}>
                                        Sign up!
                                    </Button>
                                </Box>
                            </Stack>
                        </Box>
                    </Box>
                </Box>
            </main>
        </>
    );
    return (
        <>
            <Head>
                <title>Upfront - Jobs</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/upfront/svg/favicon-no-background.svg"
                />
            </Head>
            <main>
                <Container maxWidth={{ base: "100%", md: "70%", lg: "60%" }}>
                    <Navbar />
                    <HStack justifyContent={"space-between"}>
                        <Text>Upfront Jobs</Text>
                        <Button as="a" onClick={() => router.push("/jobPost")}>
                            Post a job
                        </Button>
                    </HStack>
                    <Text fontWeight={700} my="1rem">
                        Carefully selected job postings where salary ranges are
                        guaranteed to be listed.
                    </Text>
                    <Text fontWeight={700} mb="1rem">
                        Data-driven insights into job posting performance for
                        recruiters and companies.
                    </Text>
                    <JobSearch />
                </Container>
            </main>
        </>
    );
}
