import Head from "next/head";
import Navbar from "../components/Navbar";
import {
    Box,
    Button,
    Center,
    Checkbox,
    Container,
    HStack,
    Icon,
    Image,
    Input,
    Select,
    Text,
    VStack,
} from "@chakra-ui/react";
const SimpleMdeReact = dynamic(() => import("react-simplemde-editor"), {
    ssr: false,
});
import { useCallback, useRef, useState } from "react";
import dynamic from "next/dynamic";
import "easymde/dist/easymde.min.css";
import { AddIcon } from "@chakra-ui/icons";
import Markdown from "react-markdown";

export default function Home() {
    const hiddenFileInput = useRef(null);
    const [title, setTitle] = useState<string>();
    const [location, setLocation] = useState<string>();
    const [minimumSalary, setMinimumSalary] = useState<string>();
    const [maximumSalary, setMaximumSalary] = useState<string>();
    const [currency, setCurrency] = useState<string>();
    const [description, setDescription] = useState(
        "Write your Job Description here!"
    );
    const [companyName, setCompanyName] = useState<string>();
    const [companyWebsite, setCompanyWebsite] = useState<string>();
    const [visaSponsorship, setVisaSponsorship] = useState(false);
    const onChange = useCallback((value: string) => {
        setDescription(value);
    }, []);

    const [file, setFile] = useState<string>();
    const [fileName, setFileName] = useState<string>();
    const [applyUrl, setApplyUrl] = useState("");
    const [recruiterEmail, setRecruiterEmail] = useState("");

    const handleClick = () => {
        if (hiddenFileInput.current) {
            (hiddenFileInput?.current as any).click();
        }
    };

    // const handleChange = (event: any) => {
    //     const fileUploaded = event.target.files[0];
    //     setFile(fileUploaded);
    // };

    function fileUploadInputChange(e: any) {
        let reader = new FileReader();
        reader.onload = function (e) {
            setFile(e.target?.result as string);
        };
        reader.readAsDataURL(e.target.files[0]);
        setFileName(e.target.files[0].name);
    }

    console.log(typeof file);

    return (
        <>
            <Head>
                <title>Upfront - Post a Job</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/upfront/svg/favicon-no-background.svg"
                />
            </Head>
            <main>
                <Container
                    maxWidth={{ base: "100%", md: "70%", lg: "60%" }}
                    mb="1rem"
                >
                    <Navbar />
                    <Text mb="1rem">Post a Job</Text>
                    <Text fontWeight={"700"} mb="1rem">
                        We require that companies are Upfront about their
                        salaries. All job postings must contain a salary range.
                    </Text>
                    <Center>
                        <VStack width="80%" alignItems={"start"} mb="1rem">
                            <Text
                                fontWeight={"700"}
                                fontSize={"2rem"}
                                mb="0.5rem"
                            >
                                Create a Job Post:
                            </Text>
                            <Input
                                type="text"
                                placeholder="Job Title"
                                mb="0.5rem"
                                onChange={(e) =>
                                    setTitle(e.target.value as string)
                                }
                                value={title}
                            />
                            <Input
                                type="text"
                                placeholder="Job Location"
                                mb="0.5rem"
                                onChange={(e) => setLocation(e.target.value)}
                                value={location}
                            />
                            <HStack width="100%" mb="0.5rem">
                                <Input
                                    type="number"
                                    placeholder="Min Annual Salary"
                                    onChange={(e) =>
                                        setMinimumSalary(e.target.value)
                                    }
                                    value={minimumSalary}
                                />
                                <Input
                                    type="number"
                                    placeholder="Max Annual Salary"
                                    onChange={(e) =>
                                        setMaximumSalary(e.target.value)
                                    }
                                    value={maximumSalary}
                                />
                                <Select
                                    onChange={(e) =>
                                        setCurrency(e.target.value)
                                    }
                                >
                                    <option>GBP</option>
                                    <option>USD</option>
                                    <option>EUR</option>
                                    <option>AUD</option>
                                    <option>CAD</option>
                                    <option>SGD</option>
                                    <option>CHF</option>
                                    <option>INR</option>
                                    <option>JPY</option>
                                </Select>
                                <Text>a year</Text>
                            </HStack>
                            <Input
                                type="text"
                                placeholder="Company Name"
                                mb="0.5rem"
                                onChange={(e) => setCompanyName(e.target.value)}
                                value={companyName}
                            />
                            <Input
                                type="text"
                                placeholder="Company Website"
                                mb="0.5rem"
                                onChange={(e) =>
                                    setCompanyWebsite(e.target.value)
                                }
                                value={companyWebsite}
                            />
                            <HStack>
                                <Button
                                    className="button-upload"
                                    onClick={handleClick}
                                    bg={"upfront.300"}
                                    _hover={{
                                        bg: "upfront.200",
                                    }}
                                    color="white"
                                    mb="0.5rem"
                                >
                                    <AddIcon mr="0.5rem" />
                                    Upload Company Logo
                                </Button>
                                <input
                                    type="file"
                                    accept="image/*"
                                    onChange={fileUploadInputChange}
                                    ref={hiddenFileInput}
                                    style={{ display: "none" }} // Make the file input element invisible
                                />
                                {fileName && <Text>{fileName}</Text>}
                            </HStack>

                            <SimpleMdeReact
                                style={{
                                    width: "100%",
                                }}
                                value={description}
                                onChange={onChange}
                            />

                            <Checkbox
                                mb="0.5rem"
                                onChange={() =>
                                    setVisaSponsorship(!visaSponsorship)
                                }
                            >
                                VISA Sponsorship offered?
                            </Checkbox>

                            <Input
                                type="url"
                                placeholder="How to apply (Email or URL)"
                                mb="0.5rem"
                                onChange={(e) => setApplyUrl(e.target.value)}
                                value={applyUrl}
                            />
                            <Input
                                type="email"
                                placeholder="Your email (will be used to log in)"
                                mb="0.5rem"
                                onChange={(e) =>
                                    setRecruiterEmail(e.target.value)
                                }
                                value={recruiterEmail}
                            />
                            <Text mb="0.5rem" fontWeight={"700"}>
                                Preview:
                            </Text>
                            <Box border={"1px solid grey"}>
                                <HStack>
                                    {file && (
                                        <Image
                                            src={file}
                                            width="50px"
                                            borderRadius={"5px"}
                                        />
                                    )}
                                    <VStack>
                                        <Text>{`${title ?? "Job Title"} with ${
                                            companyName ?? "Company Name"
                                        }`}</Text>
                                        <Text>{`${currency}${
                                            minimumSalary ?? "Minimum Salary"
                                        } to ${currency}${
                                            minimumSalary ?? "Maximum Salary"
                                        }`}</Text>
                                        {visaSponsorship && (
                                            <Text>
                                                Visa Sponsorship Offered
                                            </Text>
                                        )}
                                        <Markdown>{description}</Markdown>
                                    </VStack>
                                </HStack>
                            </Box>
                        </VStack>
                    </Center>
                </Container>
            </main>
        </>
    );
}
