import Head from "next/head";
import { Box, Text } from "@chakra-ui/react";
import Layout from "@/components/Layout";
import useSWR from "swr";
import { useRouter } from "next/router";
import { fetchGetJSON } from "@/utils/api-helpers";

export default function Success() {
    const router = useRouter();

    const { data, error } = useSWR(
        router.query.session_id
            ? `/api/checkout_sessions/${router.query.session_id}`
            : null,
        fetchGetJSON
    );

    if (error) return <div>failed to load</div>;

    return (
        <>
            <Head>
                <title>Upfront - Jobs</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/upfront/svg/favicon-no-background.svg"
                />
            </Head>
            <Layout>
                <Text fontSize={"2.5rem"} fontWeight={700} my="1rem">
                    Don&apos;t waste time. Be{" "}
                    <Text as="span" fontWeight="800" color={"upfront.300"}>
                        Upfront.
                    </Text>
                </Text>
                <Text fontWeight={700} fontSize={"2rem"} mb="1rem">
                    Where{" "}
                    <Text as="span" fontWeight="800" color={"upfront.300"}>
                        salaries
                    </Text>{" "}
                    are always{" "}
                    <Text as="span" fontWeight="800" color={"upfront.300"}>
                        provided.
                    </Text>
                </Text>
                <div className="page-container">
                    <h1>Checkout Payment Result</h1>
                    <h2>
                        Status: {data?.payment_intent?.status ?? "loading..."}
                    </h2>
                    <h3>CheckoutSession response:</h3>
                    <Box>{data?.id ?? "loading..."}</Box>
                </div>
            </Layout>
        </>
    );
}
