import Head from "next/head";
import { Text } from "@chakra-ui/react";
import Layout from "@/components/Layout";

export default function Success() {
    return (
        <>
            <Head>
                <title>Upfront - Jobs</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/upfront/svg/favicon-no-background.svg"
                />
            </Head>
            <Layout>
                <Text fontSize={"2.5rem"} fontWeight={700} my="1rem">
                    Don&apos;t waste time. Be{" "}
                    <Text as="span" fontWeight="800" color={"upfront.300"}>
                        Upfront.
                    </Text>
                </Text>
                <Text fontWeight={700} fontSize={"2rem"} mb="1rem">
                    Where{" "}
                    <Text as="span" fontWeight="800" color={"upfront.300"}>
                        salaries
                    </Text>{" "}
                    are always{" "}
                    <Text as="span" fontWeight="800" color={"upfront.300"}>
                        provided.
                    </Text>
                </Text>
                <Text fontSize="3rem">Payment Successful!</Text>
            </Layout>
        </>
    );
}
